apiVersion: v1
kind: Service
metadata:
  name: item-service
  namespace: default
  labels:
    app: item-service
spec:
  selector:
    app: item-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
