apiVersion: v1
kind: Service
metadata:
  name: anne-api
  namespace: default
  labels:
    app: anne-api
spec:
  selector:
    app: anne-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
